studysymblog:
    resource: "@studysymblogBundle/Controller/"
    type:     annotation
    prefix:   /

study_model:
    resource: "@studyModelBundle/Controller/"
    type:     annotation
    prefix:   /

